"""Solvent accessibility by the Shrake-Rupley algorithm (A.13).

The implementation is deliberately self-contained and deterministic: the sphere
point set is generated by a fixed golden-spiral rule, the radii table is
versioned in :mod:`pdbthink.chem`, and all retained assembly atoms occlude.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from functools import lru_cache

import numpy as np
from scipy.spatial import cKDTree

from ..chem import MAX_ASA_VERSION, RADII_VERSION, max_asa, vdw_radius
from ..config import Definitions
from ..preprocessing.model import Structure

BURIED = "buried"
EXPOSED = "solvent-exposed"
INTERMEDIATE = "intermediate"


@dataclass
class SasaResult:
    atom_sasa: np.ndarray                              # (n_atoms,) square Angstrom
    residue_sasa: dict[int, float] = field(default_factory=dict)
    residue_rasa: dict[int, float | None] = field(default_factory=dict)
    probe_radius: float = 1.4
    n_points: int = 960
    radii_version: str = RADII_VERSION
    max_asa_version: str = MAX_ASA_VERSION

    def classify(self, residue_index: int, definitions: Definitions) -> str:
        cfg = definitions.get("solvent_accessibility")
        rasa = self.residue_rasa.get(residue_index)
        if rasa is None:
            return INTERMEDIATE
        if rasa <= float(cfg["buried_max_rasa"]):
            return BURIED
        if rasa >= float(cfg["exposed_min_rasa"]):
            return EXPOSED
        return INTERMEDIATE


@lru_cache(maxsize=8)
def sphere_points(n: int) -> np.ndarray:
    """``n`` quasi-uniform points on the unit sphere (golden spiral, v1)."""
    k = np.arange(n, dtype=float)
    offset = 2.0 / n
    z = k * offset - 1.0 + offset / 2.0
    r = np.sqrt(np.maximum(0.0, 1.0 - z * z))
    phi = k * np.pi * (3.0 - np.sqrt(5.0))
    return np.stack([np.cos(phi) * r, np.sin(phi) * r, z], axis=1)


def compute_sasa(structure: Structure, definitions: Definitions) -> SasaResult:
    """Per-atom and per-residue solvent-accessible surface area."""
    cfg = definitions.get("solvent_accessibility")
    probe = float(cfg["probe_radius"])
    n_points = int(cfg["n_sphere_points"])

    index = structure.index
    coords = index.coords
    n_atoms = len(coords)
    if n_atoms == 0:
        return SasaResult(atom_sasa=np.zeros(0), probe_radius=probe, n_points=n_points)

    radii = np.array([vdw_radius(e) for e in index.elements], dtype=float)
    expanded = radii + probe
    unit = sphere_points(n_points)
    tree = cKDTree(coords)
    max_reach = float(expanded.max() * 2)
    neighbour_lists = tree.query_ball_point(coords, max_reach)

    atom_sasa = np.zeros(n_atoms, dtype=float)
    for i in range(n_atoms):
        ri = expanded[i]
        neighbours = [j for j in neighbour_lists[i] if j != i]
        if neighbours:
            nb = np.asarray(neighbours, dtype=int)
            deltas = coords[nb] - coords[i]
            d = np.linalg.norm(deltas, axis=1)
            keep = d < (ri + expanded[nb])
            nb, deltas = nb[keep], deltas[keep]
        else:
            nb = np.zeros(0, dtype=int)
            deltas = np.zeros((0, 3))
        test = unit * ri                                    # relative to atom i
        if len(nb):
            # (n_points, n_neighbours) squared distances
            diff = test[:, None, :] - deltas[None, :, :]
            dist2 = np.einsum("ijk,ijk->ij", diff, diff)
            buried = (dist2 < (expanded[nb] ** 2)[None, :]).any(axis=1)
            accessible = int((~buried).sum())
        else:
            accessible = n_points
        atom_sasa[i] = 4.0 * np.pi * ri * ri * accessible / n_points

    residue_sasa: dict[int, float] = {}
    for gi in range(n_atoms):
        ri = int(index.residue_of[gi])
        residue_sasa[ri] = residue_sasa.get(ri, 0.0) + float(atom_sasa[gi])

    residue_rasa: dict[int, float | None] = {}
    for ri, total in residue_sasa.items():
        res = structure.residues[ri]
        reference = max_asa(res.orig_name) if res.is_protein else None
        residue_rasa[ri] = None if not reference else total / reference

    return SasaResult(
        atom_sasa=atom_sasa,
        residue_sasa=residue_sasa,
        residue_rasa=residue_rasa,
        probe_radius=probe,
        n_points=n_points,
    )


def isolated_chain_rasa(
    structure: Structure, chain: str, definitions: Definitions
) -> dict[str, float]:
    """Relative ASA per residue label for one chain computed in isolation (A.31).

    Keyed by label rather than index because the subset renumbers residues.
    """
    keep = [i for i, r in enumerate(structure.residues) if r.chain == chain]
    isolated = structure.subset(keep)
    result = compute_sasa(isolated, definitions)
    out: dict[str, float] = {}
    for ri, rasa in result.residue_rasa.items():
        if rasa is not None:
            out[isolated.residues[ri].label] = rasa
    return out
