"""Harbor adapter for a single text completion, with no model-accessible tools.

Harbor is optional. Import this module only in a Harbor Python environment.
Budgets must come from an endpoint-appropriate, exact token-count manifest;
reference cl100k counts in the dataset are not native model token counts.
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import os
import urllib.request
from pathlib import Path

from harbor.agents.base import BaseAgent

from .protocol import request_payload, tool_events


class CoordinateNoToolsAgent(BaseAgent):
    """The host writes the answer file; the model sees only coordinate text."""

    def __init__(
        self,
        *args,
        endpoint=None,
        api_key_env="OPENAI_API_KEY",
        budget_manifest=None,
        request_extra=None,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)
        if not endpoint or not budget_manifest:
            raise ValueError("endpoint and exact budget_manifest are required")
        self.endpoint = endpoint.rstrip("/") + "/chat/completions"
        self.api_key_env = api_key_env
        self.budgets = json.loads(Path(budget_manifest).read_text())
        self.request_extra = (
            json.loads(request_extra) if isinstance(request_extra, str) else (request_extra or {})
        )
        if self.mcp_servers:
            raise ValueError("coordinate tasks prohibit MCP servers")

    @staticmethod
    def name() -> str:
        return "pdbthink-no-tools"

    def version(self) -> str:
        return "1.0.0"

    async def setup(self, environment) -> None:
        return None

    async def run(self, instruction, environment, context) -> None:
        # This separator is generated by task_archives; neither portion contains
        # evaluator-only files, source metadata, gold answers or oracle evidence.
        marker = "\n\nYou are given "
        if marker not in instruction:
            raise ValueError("unrecognised coordinate instruction envelope")
        system, rest = instruction.split(marker, 1)
        user = "You are given " + rest
        key = hashlib.sha256((system + "\n" + user).encode()).hexdigest()
        if key not in self.budgets:
            raise ValueError(f"no exact per-prompt budget for {key}")
        payload = request_payload(
            self.model_name,
            [{"role": "system", "content": system}, {"role": "user", "content": user}],
            self.budgets[key],
            extra=self.request_extra,
        )
        self.logs_dir.mkdir(parents=True, exist_ok=True)
        (self.logs_dir / "request.json").write_text(json.dumps(payload, indent=2))
        (self.logs_dir / "budget.json").write_text(json.dumps(self.budgets[key], indent=2))

        def send():
            headers = {"Content-Type": "application/json"}
            if os.environ.get(self.api_key_env):
                headers["Authorization"] = "Bearer " + os.environ[self.api_key_env]
            request = urllib.request.Request(
                self.endpoint, data=json.dumps(payload).encode(), headers=headers
            )
            with urllib.request.urlopen(request, timeout=7000) as response:
                return response.read()

        raw = await asyncio.to_thread(send)
        (self.logs_dir / "raw_response.json").write_bytes(raw)
        response = json.loads(raw)
        choice = response["choices"][0]
        content = choice["message"].get("content") or ""
        if not isinstance(content, str):
            raise ValueError("expected a text-only response")
        status = {
            "protocol": "pdbthink-tool-free-v1",
            "truncated": choice.get("finish_reason") == "length",
            "provider_refusal": bool(choice["message"].get("refusal")),
            "tool_events": tool_events(response),
            "requested_output_tokens": payload["max_tokens"],
            "usage": response.get("usage", {}),
            "prompt_sha256": key,
            "finish_reason": choice.get("finish_reason"),
        }
        if status["truncated"]:
            status["needs_budget_audit"] = True
        answer_path = self.logs_dir / "answer.txt"
        answer_path.write_text(content)
        status_path = self.logs_dir / "answer_status.json"
        status_path.write_text(json.dumps(status, indent=2))
        await environment.upload_file(source_path=answer_path, target_path="/app/answer.txt")
        await environment.upload_file(source_path=status_path, target_path="/app/answer_status.json")
